FROM node:20.12.0

WORKDIR /app

COPY . /app

RUN npm install

RUN apt-get update && apt-get install -y postgresql-client

COPY scripts/setupTesting.sh /scripts/setupTesting.sh

RUN chmod +x /scripts/setupTesting.sh

ENTRYPOINT ["bash", "-c", "/scripts/setupTesting.sh && npm test"]
